CREATE OR REPLACE PROCEDURE DEMO_DB.DEMO.TEST_STORED_PROCEDURE()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN

CREATE OR REPLACE TABLE DEMO_DB.DEMO.HELLO_WORLD_2 
AS (
SELECT * FROM DEMO_DB.DEMO.HELLO_WORLD
);

RETURN 'Table created successfully.';

END
;

call DEMO_DB.DEMO.TEST_STORED_PROCEDURE();